version: "3"
services:
# ------------Support services-------------
  curriculum_db:
    image: mongo
    container_name: curriculum_db
  learningplatform_db:
    image: mysql:5.7
    container_name: learningplatform_db
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=learningplatform
  zookeeper:
    image: confluentinc/cp-zookeeper
    environment:
      - ZOOKEEPER_CLIENT_PORT=2181
  kafka:
    image: confluentinc/cp-kafka
    depends_on: 
      - zookeeper
    environment: 
      - KAFKA_BROKER_ID=1
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1

# ------------Core services----------------
  learningplatform:
    build: ./learningPlatform
    container_name: learningplatform
    links:
      - learningplatform_db
      - kafka
    depends_on:
      - learningplatform_db
      - kafka
    environment:
      - spring.cloud.stream.kafka.binder.brokers=kafka
      - spring.cloud.stream.kafka.binder.zkNodes=zookeeper
  notification:
    build: ./notification
    container_name: notification
    links:
      - kafka
    depends_on:
      - kafka
    environment:
      - spring.cloud.stream.kafka.binder.brokers=kafka
      - spring.cloud.stream.kafka.binder.zkNodes=zookeeper
  curriculum:
    build: ./curriculum
    container_name: curriculum
    links:
      - curriculum_db
      - kafka
    depends_on:
      - curriculum_db
      - kafka
      - learningplatform
    environment: 
      - spring.cloud.stream.kafka.binder.brokers=kafka
      - spring.cloud.stream.kafka.binder.zkNodes=zookeeper
      - spring.data.mongodb.host=curriculum_db
      - spring.data.mongodb.port=27017
  api_gw:
    build: ./api_gateway
    volumes:
      - ./api_gateway/target:/app
    links:
      - curriculum
      - learningplatform
    depends_on:
      - curriculum
      - learningplatform
    environment:
      - CURRICULUM_HOST=curriculum
      - FACULTY_HOST=faculty
      - LEARNINGPLATFORM_HOST=learningplatform
      - EVALUATION_HOST=evaluation
      - ACCOUNT_HOST=account
    ports:
      - 80:8080
    container_name: api_gateway
  faculty:
    build: ./faculty
    container_name: faculty
    links:
      - kafka
    depends_on:
      - kafka
      - learningplatform
    environment:
      - spring.cloud.stream.kafka.binder.brokers=kafka
      - spring.cloud.stream.kafka.binder.zkNodes=zookeeper
  evaluation:
    build: ./evaluation
    container_name: evaluation
    links:
      - kafka
    depends_on:
      - kafka
      - faculty
      - curriculum
    environment:
      - spring.cloud.stream.kafka.binder.brokers=kafka
      - spring.cloud.stream.kafka.binder.zkNodes=zookeeper
  account:
    build: ./account
    container_name: account
    links:
      - kafka
    depends_on:
      - kafka
    environment:
      - spring.cloud.stream.kafka.binder.brokers=kafka
      - spring.cloud.stream.kafka.binder.zkNodes=zookeeper
