version: "3"
services:
# ------------Support services-------------
  curriculum_db:
    image: mongo
    container_name: curriculum_db
  faculty_curriculum_db:
    image: mongo
    container_name: faculty_curriculum_db
  zookeeper:
    image: confluentinc/cp-zookeeper
    environment:
      - ZOOKEEPER_CLIENT_PORT=2181
  kafka:
    image: confluentinc/cp-kafka
    depends_on: 
      - zookeeper
    environment: 
      - KAFKA_BROKER_ID=1
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1

# ------------Core services----------------
  curriculum:
    build: ./curriculum
    container_name: curriculum
    links:
      - curriculum_db
      - faculty_curriculum_db
      - kafka
    depends_on:
      - curriculum_db
      - faculty_curriculum_db
      - kafka
    environment: 
      - spring.cloud.stream.kafka.binder.brokers=kafka
      - spring.cloud.stream.kafka.binder.zkNodes=zookeeper
      - spring.data.mongodb.host=curriculum_db
      - spring.data.mongodb.host=faculty_curriculum_db
      - spring.data.mongodb.port=27017
  faculty:
    build: ./faculty
    container_name: faculty
    links:
      - kafka
    depends_on:
      - kafka
    environment:
      - spring.cloud.stream.kafka.binder.brokers=kafka
      - spring.cloud.stream.kafka.binder.zkNodes=zookeeper
  notification:
    build: ./notification
    container_name: notification
    links:
      - kafka
    depends_on:
      - kafka
    environment:
      - spring.cloud.stream.kafka.binder.brokers=kafka
      - spring.cloud.stream.kafka.binder.zkNodes=zookeeper
  api_gw:
    build: ./api_gateway
    volumes:
      - ./api_gateway/target:/app
    links:
      - curriculum
    depends_on:
      - curriculum
    ports:
      - 80:8080
    container_name: api_gateway
